language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  labeling_instructions: []
  path_filters:
    - '!node_modules/**'
    - '!ios/build/**'
    - '!ios/Pods/**'
    - '!coverage/**'
    - '!*.lock'
    - '!package-lock.json'
    - '!Gemfile.lock'
    - '!fastlane/**'
    - '!ios/Jellyfin.xcworkspace/**'
    - '!ios/Jellyfin.xcodeproj/**'
  path_instructions:
    - path: '**/*.{js,jsx,ts,tsx}'
      instructions: |
        - Focus on React Native best practices and performance
        - Check for proper prop validation and TypeScript types
        - Look for potential memory leaks in useEffect hooks
        - Ensure proper error handling in async operations
        - Verify accessibility considerations for mobile apps
        - Check for proper state management patterns with Zustand
    - path: stores/**
      instructions: |
        - Review Zustand store implementations for proper state management
        - Check for proper serialization/deserialization patterns
        - Ensure stores follow the established patterns in the codebase
        - Verify that async operations are properly handled
    - path: components/**
      instructions: |
        - Focus on component reusability and composition
        - Check for proper prop types and default values
        - Ensure components follow React Native styling patterns
        - Verify accessibility props are properly implemented
    - path: '**/*.test.{js,jsx,ts,tsx}'
      instructions: |
        - Review test coverage and quality
        - Ensure tests follow Jest and React Native Testing Library best
        practices
        - Check for proper mocking of native modules
        - Verify async operations are properly tested
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: warning
      requirements: >
        Title should be concise and descriptive, ideally under 50 characters.
        Title should use the imperative mood, be capitalized, and not end with punctuation.
        Conventional Commit style formatting is prohibited.
    description:
      mode: warning
    issue_assessment:
      mode: warning
chat:
  auto_reply: true
